apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
  labels:
    app: backstage
data:
  app-config.k8s.yaml: |
    # This will be populated by Kustomize from app-config.k8s.yaml
    # See kustomization.yaml configMapGenerator
