apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: backstage

# Resources to include
resources:
- deployment.yaml
- service.yaml
- ingress.yaml

# labels applied to all resources

# Common annotations applied to all resources
commonAnnotations:
  app.kubernetes.io/version: 1.47.0
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/component: backend
    app.kubernetes.io/name: backstage
    app.kubernetes.io/part-of: backstage
